import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;

public class tempMenu extends javax.swing.JFrame {

    ArrayList<Model> list;
    ArrayList<Integer> priceList = new ArrayList<Integer>();
    ArrayList<String> categoryList = new ArrayList<String>();
    ArrayList<Integer> DishIdList = new ArrayList<Integer>();
    ArrayList<Model> modelList = new ArrayList<Model>();
    ArrayList<String> itemList = new ArrayList<String>();
    ArrayList<String> itemL = new ArrayList<String>();
    Map<String, Integer> order = new HashMap<>();
    Model model;

    /**
     * Creates new form Menu_System
     */
    public tempMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDishnum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDishname = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jPanel1.setBorder(
                javax.swing.BorderFactory.createTitledBorder(null, "Order Items",
                        javax.swing.border.TitledBorder.CENTER,
                        javax.swing.border.TitledBorder.DEFAULT_POSITION,
                        new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Dish ID");

        txtDishnum.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDishnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDishnumActionPerformed(evt);
            }
        });
        txtDishnum.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Dish Name");

        ArrayList<String> al1 = new ArrayList<String>();

        ConnectionClass obj = new ConnectionClass();
        String query = "SELECT * FROM food;";

        ResultSet rs;
        try {
            rs = obj.stm.executeQuery(query);
            while (rs.next()) {
                al1.add(rs.getString(2));
            }
            rs.close();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        txtDishname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDishname.setModel(new javax.swing.DefaultComboBoxModel<>(
                Arrays.copyOf(al1.toArray(), al1.toArray().length, String[].class)));
        txtDishname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dishNameStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Category");
        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox1.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Spiciness");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Hot");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Mild");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Less");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Price");

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        txtPrice.setEditable(false);
        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Quantity");

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Add To Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                false)
                                        .addComponent(jLabel5,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(jLabel4,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(jLabel3,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(jLabel2,
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                101, Short.MAX_VALUE)
                                        .addComponent(jLabel1,
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(jLabel8,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                .addGap(90, 90, 90)
                                .addGroup(jPanel1Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                        false)
                                                .addComponent(txtDishnum,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        115,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtDishname)
                                                .addComponent(jComboBox1,
                                                        0, 211,
                                                        Short.MAX_VALUE))
                                        .addComponent(txtPrice,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                93,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtQuantity,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                93,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout
                                                .createSequentialGroup()
                                                .addComponent(jRadioButton1)
                                                .addGap(10, 10, 10)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addGap(16, 16, 16)
                                                                .addComponent(jRadioButton2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        83,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jRadioButton3,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        68,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jButton1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                169,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(66, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                31,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDishnum,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                31,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                33,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDishname,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                34,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                        .addComponent(jLabel3,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(jComboBox1,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                37,
                                                Short.MAX_VALUE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                39,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jRadioButton1)
                                        .addComponent(jRadioButton2)
                                        .addComponent(jRadioButton3))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                        .addComponent(jLabel5,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(txtPrice,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                36,
                                                Short.MAX_VALUE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                        .addComponent(jLabel8,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(txtQuantity,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                36,
                                                Short.MAX_VALUE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        13,
                                        Short.MAX_VALUE)
                                .addComponent(jButton1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order Details",
                javax.swing.border.TitledBorder.CENTER,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                },
                new String[] {
                        "Dish Number", "Dish Name", "Category", "Spiciness", "Price", "Quantity"
                }) {
            Class[] types = new Class[] {
                    java.lang.Integer.class, java.lang.Object.class,
                    java.lang.Object.class, java.lang.Object.class,
                    java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        511,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        408,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Food",
                javax.swing.border.TitledBorder.CENTER,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Quantity");

        jPrice.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPriceActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Category");

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(
                Arrays.copyOf(al1.toArray(), al1.toArray().length, String[].class)));

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setText("Search Food By Price");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton5.setText("Search Food By category");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout
                                                .createSequentialGroup()
                                                .addComponent(jLabel7,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        110,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboBox2,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        102,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel6,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                101,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                        .addComponent(jButton3,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(jPrice,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                98,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton5,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                222,
                                                Short.MAX_VALUE))
                                .addGap(25, 25, 25)));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                39,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPrice,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                39,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                43,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox2,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                43,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton5,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                43,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)));

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setText("Confirm Order");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton6.setText("Delete Item");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jButton2,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        95,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        125,
                                        Short.MAX_VALUE)
                                .addComponent(jButton6,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        95,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        125,
                                        Short.MAX_VALUE)
                                .addComponent(jButton4,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        111,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton2,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                43,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton6,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                43,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton4,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                .addContainerGap(31, Short.MAX_VALUE)));

        jMenu1.setText("File");
        jMenu1.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O,
                java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Open File");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O,
                java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1,
                java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING,
                                        false)
                                        .addComponent(jPanel1,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(jPanel3,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel2,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel4,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                .createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addGap(209, 209, 209)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel1,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jPanel3,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel2,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jPanel4,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));

        pack();

    }// </editor-fold>//GEN-END:initComponents

    protected void txtQuantityActionPerformed(ActionEvent evt) {
    }

    private void txtDishnumActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtDishnumActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtDishnumActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtPriceActionPerformed

    private void jPriceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jPriceActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jPriceActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String category = jComboBox2.getSelectedItem().toString();
        int i = 0, count = 0;
        int csize = modelList.size() - 1;

        while (i <= csize) {
            if (category.equals(modelList.get(i).getCategory())) {
                count++;
                System.out.println("The cateogries are :" + modelList.get(i).getCategory());
                System.out.println("The ids are :" + modelList.get(i).getDishname());

                itemList.add(modelList.get(i).getDishname());

            }
            i++;
        }
        System.out.println(printList() + "");
        JOptionPane.showMessageDialog(null,
                count + " DISHES ARE  AVAILABE AT THIS CATEGORY: THEY ARE : " + printList(),
                "FOOD INFORMATION",
                JOptionPane.INFORMATION_MESSAGE);
        itemList.clear();

    }// GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtDishname.setSelectedIndex(0);
        txtDishnum.setText("");
        jComboBox1.setText("");
        txtPrice.setText("");
        txtQuantity.setText("");
    }// GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String dishNum = txtDishnum.getText();
            int dishm = Integer.parseInt(dishNum);
            String category = jComboBox1.getText();
            String dishName = (String) txtDishname.getSelectedItem();
            String Price = txtPrice.getText();
            String range = "";
            String Quantity = txtQuantity.getText();

            if (jRadioButton1.isSelected()) {
                range += jRadioButton1.getText();
            }
            if (jRadioButton2.isSelected()) {
                range += jRadioButton2.getText();
            }
            if (jRadioButton3.isSelected()) {
                range += jRadioButton3.getText();
            }

            if (dishName.isEmpty() || Price.isEmpty()) {
                JOptionPane.showMessageDialog(null,
                        "one or more field is empty",
                        "please insert again",
                        JOptionPane.WARNING_MESSAGE);
            } else {
                int p = Integer.parseInt(Price);
                priceList.add(p);

                itemL.add(dishName);
                model = new Model(category, dishName);

                modelList.add(model);
                categoryList.add(category);
                int dsize = DishIdList.size() - 1;
                String[] name = { dishNum, dishName, category, range, Price, Quantity };
                int rowCount = jTable1.getRowCount();
                int columnCount = jTable1.getColumnCount();
                int nextRow = 0;
                boolean emptyRowFlag = false;
                String s;
                do {
                    s = (String) jTable1.getValueAt(nextRow, 0);
                    if (s != null && s.length() != 0) {
                        nextRow++;
                    } else {
                        emptyRowFlag = true;
                    }
                } while (nextRow < rowCount && !emptyRowFlag);
                for (int i = 0; i < columnCount; i++) {
                    jTable1.setValueAt(name[i], nextRow, i);
                }

                DishIdList.add(dishm);
                order.put(dishName, Integer.parseInt(Quantity));

                txtDishname.setSelectedIndex(0);
                txtDishnum.setText("");
                jComboBox1.setText("");
                txtPrice.setText("");
                txtQuantity.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid input."
                    + "Enter Number only");
            e.printStackTrace();
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        super.dispose();
    }// GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel t = ((DefaultTableModel) jTable1.getModel());
        int row = jTable1.getSelectedRow();
        order.remove(t.getValueAt(row, 0), t.getValueAt(row, 5));
        t.removeRow(jTable1.getSelectedRow());
    }// GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int price;
        price = Integer.parseInt(jPrice.getText().toString());
        Collections.sort(priceList);
        int low = 0;
        int high = priceList.size() - 1;
        int result = BinarySearch(priceList, price, low, high);

        // System.out.println(priceList.get(i));
        if (result == -1) {
            JOptionPane.showMessageDialog(null,
                    "YOUR FOOD IS  NOT AVAILABE AT this price",
                    "FOOD INFORMATION",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null,
                    "YOUR FOOD IS  AVAILABE AT this price",
                    "FOOD INFORMATION",
                    JOptionPane.INFORMATION_MESSAGE);
        }

    }// GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }// GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "
                    + "D:\\ICP\\Emerging Technology And Platforms\\Marking Scheme.pdf");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error");
        }
    }// GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,
                "This is a simple menu odering system in java netbeans.",
                "About The System",
                JOptionPane.INFORMATION_MESSAGE);
    }// GEN-LAST:event_jMenuItem2ActionPerformed

    public int BinarySearch(ArrayList<Integer> list, int x, int low, int high) {
        int mid;
        if (low <= high) {
            mid = (low + high) / 2;
            if (x == list.get(mid)) {
                return mid;
            } else if (x <= list.get(mid)) {
                return BinarySearch(list, x, low, mid - 1);
            } else
                return BinarySearch(list, x, mid + 1, high);
        }
        return -1;
    }

    public String printList() {
        String val = "";
        for (int i = 0; i <= itemList.size() - 1; i++) {
            val = val + itemList.get(i) + " , ";
        }
        return val;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JTextField jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jPrice;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> txtDishname;
    private javax.swing.JTextField txtDishnum;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;

    // End of variables declaration//GEN-END:variables

    public void dishNameStateChanged(ItemEvent e) {
        // TODO Auto-generated method stub
        System.out.println("Changed");
        ConnectionClass obj = new ConnectionClass();
        String q = "select * from food where dishName like '" + txtDishname.getSelectedItem() + "';";
        ResultSet rs;

        try {
            rs = obj.stm.executeQuery(q);
            while (rs.next()) {
                txtDishnum.setText(rs.getString(1));
                jComboBox1.setText(rs.getString(3));
                txtPrice.setText(rs.getString(4));
            }
            rs.close();
        } catch (SQLException er) {
            // TODO Auto-generated catch block
            er.printStackTrace();
        }
    }
}
